name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  VERSION: '1.0.3'

jobs:
  build:
    name: Build libgrabkernel2
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Install ldid
        run: brew install ldid

      - name: Build libgrabkernel2
        run: |
          make TARGET=ios DISABLE_TESTS=1 STATIC_ONLY=1
      - name: Upload libgrabkernel2
        uses: actions/upload-artifact@v4
        with:
          name: libgrabkernel2
          path: libgrabkernel2/output/ios/lib/libgrabkernel2.a
          retention-days: 365